#!/usr/bin/env bash
# Whole-stack launcher.
#   infra (mongo + redis) via `docker stack deploy` → seed → backend → workers → frontend
#
# SecureShield runs its OWN Mongo + Redis (no auth) rather than depending on any
# host-installed/standard-port service. Host ports are chosen DYNAMICALLY: each
# service gets the first free port at/above its base, while any port already held
# by one of our own running containers is reused (so Mongo keeps its data volume
# and ports stay stable across runs). `docker stack deploy` is idempotent.
set -euo pipefail

# Ensure Homebrew paths are available in non-interactive shells.
if [ -d /opt/homebrew/bin ]; then
  export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
elif [ -d /usr/local/bin ]; then
  export PATH="/usr/local/bin:$PATH"
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

STACK_NAME="secureshield"
GEN_STACK="$ROOT/.stack.generated.yml"
MONGO_BASE=27017
REDIS_BASE=6379

# True if a TCP port already has a listener on localhost.
port_open() { (echo > "/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1; }

wait_for_port() {
  local name=$1 port=$2
  echo "▶ Waiting for $name on :${port}…"
  until port_open "$port"; do sleep 1; done
  echo "  ✓ $name is up"
}

ensure_env() {
  local key=$1 val=$2 file=$3
  if grep -q "^${key}=" "$file"; then
    sed -i '' "s|^${key}=.*|${key}=${val}|" "$file"
  else
    printf '%s=%s\n' "$key" "$val" >> "$file"
  fi
}

# Published host ports currently held by our OWN running containers.
OUR_PORTS="$(docker ps --format '{{.Names}} {{.Ports}}' 2>/dev/null \
  | grep '^secureshield_' | grep -oE ':[0-9]+->' | tr -d ':->-' | sort -u || true)"
is_ours() { printf '%s\n' "$OUR_PORTS" | grep -qx "$1"; }

# First free port at/above the base; a port we already own counts as available.
pick_port() {
  local p=$1
  while port_open "$p" && ! is_ours "$p"; do p=$((p + 1)); done
  echo "$p"
}

gen_stack() {
  local mp=$1 rp=$2
  cat > "$GEN_STACK" <<EOF
# AUTO-GENERATED by start.sh — do not edit. Ports chosen to avoid host conflicts.
version: "3.8"
services:
  mongo:
    image: mongo:7
    ports:
      - { target: 27017, published: ${mp}, protocol: tcp, mode: host }
    volumes:
      - mongo_data:/data/db
    deploy:
      replicas: 1
      restart_policy: { condition: any }
  redis:
    image: redis:7-alpine
    ports:
      - { target: 6379, published: ${rp}, protocol: tcp, mode: host }
    deploy:
      replicas: 1
      restart_policy: { condition: any }
volumes:
  mongo_data:
EOF
}

# ── Remove stale plain-`docker compose` containers from earlier runs ──────────
for stale in secureshield-mongo secureshield-redis; do
  if docker ps -aq -f "name=^${stale}$" | grep -q .; then
    echo "▶ Removing stale container ${stale}…"
    docker rm -f "$stale" >/dev/null 2>&1 || true
  fi
done

# ── Choose ports and deploy SecureShield's own infra stack ───────────────────
MONGO_PORT=$(pick_port "$MONGO_BASE")
REDIS_PORT=$(pick_port "$REDIS_BASE")
MONGODB_URI="mongodb://localhost:${MONGO_PORT}/secureshield"
REDIS_URL="redis://localhost:${REDIS_PORT}"

if ! docker info 2>/dev/null | grep -qi 'Swarm: active'; then
  echo "▶ Initializing Docker Swarm…"
  docker swarm init --advertise-addr 127.0.0.1 >/dev/null 2>&1 \
    || docker swarm init >/dev/null 2>&1 || true
fi

echo "▶ Deploying infra stack '$STACK_NAME' (mongo :$MONGO_PORT, redis :$REDIS_PORT)…"
gen_stack "$MONGO_PORT" "$REDIS_PORT"
docker stack deploy -c "$GEN_STACK" "$STACK_NAME"

wait_for_port "MongoDB" "$MONGO_PORT"
wait_for_port "Redis" "$REDIS_PORT"

# ── App env — point the backend at SecureShield's dedicated infra ─────────────
if [ ! -f backend/.env ]; then
  echo "▶ Creating backend/.env from example…"
  cp backend/.env.example backend/.env
fi
ensure_env "MONGODB_URI" "$MONGODB_URI" backend/.env
ensure_env "REDIS_URL" "$REDIS_URL" backend/.env

echo "▶ Installing dependencies…"
(cd backend && npm install --no-audit --no-fund)
(cd frontend && npm install --no-audit --no-fund)

echo "▶ Seeding database (idempotent)…"
(cd backend && npm run seed)

echo "▶ Launching backend, workers, and frontend…"
(cd backend && npm run dev) &
BACKEND_PID=$!
(cd backend && npm run worker) &
WORKER_PID=$!
(cd frontend && npm run dev) &
FRONTEND_PID=$!

trap 'echo "Stopping…"; kill $BACKEND_PID $WORKER_PID $FRONTEND_PID 2>/dev/null || true' INT TERM

LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"

echo ""
echo "✅ SecureShield is up:"
echo "   Frontend → http://localhost:5173"
[ -n "$LAN_IP" ] && echo "   On LAN   → http://${LAN_IP}:5173   (open this on other devices)"
echo "   API      → http://localhost:4000/api/health"
echo "   Mongo    → localhost:${MONGO_PORT}   Redis → localhost:${REDIS_PORT}"
echo "   Admin    → admin@secureshield.in / ChangeMe123!"
echo ""
echo "   Stop infra with:  docker stack rm $STACK_NAME"
echo ""
wait
